### ISSUE TITLE
Home assistant Error

### ISSUE THREAD

**Issue by brunohorta82** [colinodell/python-qnapstats#17]
2018-04-27 11:58:25 ERROR (SyncWorker_10) [homeassistant.components.sensor.qnap] Failed to fetch QNAP stats from the NAS
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.6/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/srv/homeassistant/lib/python3.6/site-packages/urllib3/connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/usr/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.6/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/srv/homeassistant/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/srv/homeassistant/lib/python3.6/site-packages/urllib3/util/retry.py", line 357, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/srv/homeassistant/lib/python3.6/site-packages/urllib3/packages/six.py", line 686, in reraise
    raise value
  File "/srv/homeassistant/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/srv/homeassistant/lib/python3.6/site-packages/urllib3/connectionpool.py", line 389, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/srv/homeassistant/lib/python3.6/site-packages/urllib3/connectionpool.py", line 309, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='192.168.2.10', port=8080): Read timed out. (read timeout=5)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/components/sensor/qnap.py", line 192, in update
    self.data["system_stats"] = self._api.get_system_stats()
  File "/srv/homeassistant/lib/python3.6/site-packages/qnapstats/qnap_stats.py", line 207, in get_system_stats
    force_list=("DNS_LIST")
  File "/srv/homeassistant/lib/python3.6/site-packages/qnapstats/qnap_stats.py", line 67, in _get_url
    self._init_session()
  File "/srv/homeassistant/lib/python3.6/site-packages/qnapstats/qnap_stats.py", line 49, in _init_session
    if self._login() is False:
  File "/srv/homeassistant/lib/python3.6/site-packages/qnapstats/qnap_stats.py", line 57, in _login
    result = self._execute_post_url("authLogin.cgi", data, False)
  File "/srv/homeassistant/lib/python3.6/site-packages/qnapstats/qnap_stats.py", line 97, in _execute_post_url
    resp = self._session.post(url, data, timeout=self._timeout, verify=self._verify_ssl)
  File "/srv/homeassistant/lib/python3.6/site-packages/requests/sessions.py", line 555, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/srv/homeassistant/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/srv/homeassistant/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/srv/homeassistant/lib/python3.6/site-packages/requests/adapters.py", line 521, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='192.168.2.10', port=8080): Read timed out. (read timeout=5)

**Comment by colinodell** [comment]
> requests.exceptions.ReadTimeout: HTTPConnectionPool(host='192.168.2.10', port=8080): Read timed out. (read timeout=5)

Read timeouts usually indicate some kind of networking issue, or that your device is not responding on that IP and port.  I would recommend that you check the following:

1. Confirm that the IP of your NAS is `192.168.2.10`
2. Confirm that you can load <http://192.168.2.10:8080> in your browser
3. Try running this command on your HASS server: `nc -vz 192.168.2.10 8080` - it should connect instantly.

Hopefully those troubleshooting steps will help you uncover the issue :)
