### ISSUE TITLE
Admin only user?

### ISSUE THREAD

**Issue by SP410** [colinodell/python-qnapstats#19]
Please provide the following information along with your issue report (replace anything inside of `<>`):

**Device Model Number**: TS-251

**QTS Version**: 4.2.3

If you're reporting a `KeyError`, please also provide the XML response from your QNAP device.  You can easily obtain this by running the `debug.py` script.

**XML/Debug Output:**
~~~
Sun Jul 08 2018 23:06:45 GMT-0500 (Central Daylight Time)

Error while setting up platform qnap
Traceback (most recent call last):
  File "/usr/src/app/homeassistant/helpers/entity_platform.py", line 129, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT, loop=hass.loop)
  File "/usr/local/lib/python3.6/asyncio/tasks.py", line 358, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/app/homeassistant/components/sensor/qnap.py", line 134, in setup_platform
    for nic in config.get(CONF_NICS, api.data["system_stats"]["nics"]):
TypeError: 'NoneType' object is not subscriptable
~~~

It seems the above error occurs when using a non-admin user.  Can you confirm that this package only works with administrators on the NAS?

**Comment by colinodell** [comment]
I've just tested with a non-admin user and can confirm your findings - it seems that QTS will only provide this data to admin users.
