### ISSUE TITLE
Compatible with two factor authentication ?

### ISSUE THREAD

**Issue by nono313** [colinodell/python-qnapstats#41]
**Device Model Number**: TS-230

**QTS Version**: 4.4.3

I am trying to setup Home-Assistant integration for QNAP NAS. When initializing, I get the following error message : 

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/qnap/sensor.py", line 194, in update
    self.data["system_stats"] = self._api.get_system_stats()
  File "/usr/local/lib/python3.7/site-packages/qnapstats/qnap_stats.py", line 207, in get_system_stats
    force_list=("DNS_LIST")
  File "/usr/local/lib/python3.7/site-packages/qnapstats/qnap_stats.py", line 69, in _get_url
    result = self._execute_get_url(url, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/qnapstats/qnap_stats.py", line 82, in _execute_get_url
    self._debuglog("Appending access_token (SID: " + self._sid + ") to url")
TypeError: can only concatenate str (not "NoneType") to str
```

I do have two factor authentication enabled on my NAS and I'm wondering if it might be the cause of my issue. Is 2FA supposed to be supported ?

**Comment by colinodell** [comment]
Unfortunately it is not supported.

This is because QNAP doesn't actually provide an API - this package simulates the HTTP requests used to log into the NAS using the form, so if you have 2FA enabled it likely won't get passed that part.  I don't know if there's a good way around this based on the fact that HASS won't know the 2FA code to enter.
