### ISSUE TITLE
TS-453B Compatible?

### ISSUE THREAD

**Issue by Ferador** [colinodell/python-qnapstats#50]
Please provide the following information along with your issue report (replace anything inside of `<>`):

**Device Model Number**: TS-453B

**QTS Version**: <4.5.2.1566>

If you're reporting a `KeyError`, please also provide the XML response from your QNAP device.  You can easily obtain this by running the `debug.py` script.

**XML/Debug Output:**

Failed to fetch QNAP stats from the NAS
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/qnap/sensor.py", line 194, in update
    self.data["system_stats"] = self._api.get_system_stats()
  File "/usr/local/lib/python3.8/site-packages/qnapstats/qnap_stats.py", line 205, in get_system_stats
    resp = self._get_url(
  File "/usr/local/lib/python3.8/site-packages/qnapstats/qnap_stats.py", line 67, in _get_url
    self._init_session()
  File "/usr/local/lib/python3.8/site-packages/qnapstats/qnap_stats.py", line 49, in _init_session
    if self._login() is False:
  File "/usr/local/lib/python3.8/site-packages/qnapstats/qnap_stats.py", line 57, in _login
    result = self._execute_post_url("authLogin.cgi", data, False)
  File "/usr/local/lib/python3.8/site-packages/qnapstats/qnap_stats.py", line 98, in _execute_post_url
    return self._handle_response(resp, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/qnapstats/qnap_stats.py", line 112, in _handle_response
    auth_passed = data['authPassed']
KeyError: 'authPassed'

**Comment by Ferador** [comment]
I was able to make it work, i had to disable the force https connection inside of the qnap and set ssl and verify ssl to false. I think not forcing the connection to https isnt ideal, but thats the only way to get it working on my end, without getting that 'authPassed' KeyError. Maybe someone has an idea how to get it connecting over https. I'm not familiar with the difference between http and https.
