### ISSUE TITLE
Can't integrate a QNAP TS-251

### ISSUE THREAD

**Issue by flonair** [colinodell/python-qnapstats#51]
I cannot integrate my QNAP into HA as described here: https://github.com/home-assistant/core/issues/46637

**Device Model Number**: TS-251

**QTS Version**: 4.5.2

**XML/Debug Output:**

~~~
<2021-02-17 08:19:12 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.qnap
2021-02-17 08:19:12 DEBUG (MainThread) [homeassistant.core] Bus:Handling <Event component_loaded[L]: component=sensor>
2021-02-17 08:19:12 DEBUG (SyncWorker_6) [homeassistant.util.json] JSON file not found: /config/.storage/camera
2021-02-17 08:19:12 ERROR (SyncWorker_0) [homeassistant.components.qnap.sensor] Failed to fetch QNAP stats from the NAS
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/qnap/sensor.py", line 194, in update
    self.data["system_stats"] = self._api.get_system_stats()
  File "/usr/local/lib/python3.8/site-packages/qnapstats/qnap_stats.py", line 205, in get_system_stats
    resp = self._get_url(
  File "/usr/local/lib/python3.8/site-packages/qnapstats/qnap_stats.py", line 67, in _get_url
    self._init_session()
  File "/usr/local/lib/python3.8/site-packages/qnapstats/qnap_stats.py", line 49, in _init_session
    if self._login() is False:
  File "/usr/local/lib/python3.8/site-packages/qnapstats/qnap_stats.py", line 57, in _login
    result = self._execute_post_url("authLogin.cgi", data, False)
  File "/usr/local/lib/python3.8/site-packages/qnapstats/qnap_stats.py", line 98, in _execute_post_url
    return self._handle_response(resp, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/qnapstats/qnap_stats.py", line 112, in _handle_response
    auth_passed = data['authPassed']
KeyError: 'authPassed'>
~~~

**Comment by julien-bouquet** [comment]
Hello, 
I saw your issue, 
I have created a Pull request to add integration of TS-251 in this plugin. 
https://github.com/colinodell/python-qnapstats/pull/49
