### ISSUE TITLE
error in ha

### ISSUE THREAD

**Issue by ewallis** [colinodell/python-qnapstats#70]
Tried using ssl and no ssl, same issue

**Device Model Number**:  TVS-872XT

**QTS Version**:  4.5.4

~~~
Logger: homeassistant.components.sensor
Source: components/qnap/sensor.py:243
Integration: Sensor (documentation, issues)
First occurred: 11:27:39 AM (1 occurrences)
Last logged: 11:27:39 AM

Error while setting up qnap platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/qnap/sensor.py", line 243, in setup_platform
    for nic in config.get(CONF_NICS, api.data["system_stats"]["nics"])
TypeError: 'NoneType' object is not subscriptable

~~~

**Comment by julien-bouquet** [comment]
Hello, 
I can't find this line 
```
for nic in config.get(CONF_NICS, api.data["system_stats"]["nics"])
```
Which version is installed on your home assistant ?

**Comment by ewallis** [comment]
I believe it was 2022.4.7, thanks
