### ISSUE TITLE
QTS 5 Support

### ISSUE THREAD

**Issue by workflowsguy** [colinodell/python-qnapstats#73]
**Device Model Number**: TS-853 Pro

**QTS Version**: 5.0.0.1986

When running the code from "Usage Sample" that had worked before, it now fails with the following error:

```
Traceback (most recent call last):
  File "/Users/guy/bin/QNAP-Stats.py", line 7, in <module>
    pprint(qnap.get_system_stats())
  File "/Users/guy/Library/Python/3.10/lib/python/site-packages/qnapstats/qnap_stats.py", line 217, in get_system_stats
    resp = self._get_url(
  File "/Users/guy/Library/Python/3.10/lib/python/site-packages/qnapstats/qnap_stats.py", line 76, in _get_url
    result = self._execute_get_url(url, **kwargs)
  File "/Users/guy/Library/Python/3.10/lib/python/site-packages/qnapstats/qnap_stats.py", line 89, in _execute_get_url
    self._debuglog("Appending access_token (SID: " + self._sid + ") to url")
TypeError: can only concatenate str (not "NoneType") to str
python-BaseException
```

**Comment by workflowsguy** [comment]
Running `debug.py` gives the following output

```
Host (prefix with 'https://' if needed): https://192.168.1.11
Port: 443
Username: master
Password: 
DEBUG: Creating new session
DEBUG: POST to URL: https://192.168.1.11:443/cgi-bin/authLogin.cgi
/Users/guy/Library/Python/3.10/lib/python/site-packages/urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.1.11'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
DEBUG: Request executed: 404
DEBUG: GET from URL: https://192.168.1.11:443/cgi-bin/authLogin.cgi?user=master&pwd=ZXNrYWhzdGVmYW4=
/Users/guy/Library/Python/3.10/lib/python/site-packages/urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.1.11'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
DEBUG: Request executed: 404
DEBUG: Login failed, unable to process request
DEBUG: GET from URL: https://192.168.1.11:443/cgi-bin/management/manaRequest.cgi?subfunc=sysinfo&hd=no&multicpu=1
('can only concatenate str (not "NoneType") to str',)
Traceback (most recent call last):
  File "/Users/guy/Library/Application Support/CodeRunner/Unsaved/Untitled 7.py", line 16, in <module>
    qnap.get_system_stats()
  File "/Users/guy/Library/Python/3.10/lib/python/site-packages/qnapstats/qnap_stats.py", line 217, in get_system_stats
    resp = self._get_url(
  File "/Users/guy/Library/Python/3.10/lib/python/site-packages/qnapstats/qnap_stats.py", line 76, in _get_url
    result = self._execute_get_url(url, **kwargs)
  File "/Users/guy/Library/Python/3.10/lib/python/site-packages/qnapstats/qnap_stats.py", line 89, in _execute_get_url
    self._debuglog("Appending access_token (SID: " + self._sid + ") to url")
TypeError: can only concatenate str (not "NoneType") to str
DEBUG: Creating new session
DEBUG: POST to URL: https://192.168.1.11:443/cgi-bin/authLogin.cgi
/Users/guy/Library/Python/3.10/lib/python/site-packages/urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.1.11'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
DEBUG: Request executed: 404
DEBUG: GET from URL: https://192.168.1.11:443/cgi-bin/authLogin.cgi?user=master&pwd=ZXNrYWhzdGVmYW4=
/Users/guy/Library/Python/3.10/lib/python/site-packages/urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.1.11'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
DEBUG: Request executed: 404
DEBUG: Login failed, unable to process request
DEBUG: GET from URL: https://192.168.1.11:443/cgi-bin/management/manaRequest.cgi?subfunc=sysinfo&sysHealth=1
('can only concatenate str (not "NoneType") to str',)
Traceback (most recent call last):
  File "/Users/guy/Library/Application Support/CodeRunner/Unsaved/Untitled 7.py", line 22, in <module>
    qnap.get_system_health()
  File "/Users/guy/Library/Python/3.10/lib/python/site-packages/qnapstats/qnap_stats.py", line 130, in get_system_health
    resp = self._get_url("management/manaRequest.cgi?subfunc=sysinfo&sysHealth=1")
  File "/Users/guy/Library/Python/3.10/lib/python/site-packages/qnapstats/qnap_stats.py", line 76, in _get_url
    result = self._execute_get_url(url, **kwargs)
  File "/Users/guy/Library/Python/3.10/lib/python/site-packages/qnapstats/qnap_stats.py", line 89, in _execute_get_url
    self._debuglog("Appending access_token (SID: " + self._sid + ") to url")
TypeError: can only concatenate str (not "NoneType") to str
DEBUG: Creating new session
DEBUG: POST to URL: https://192.168.1.11:443/cgi-bin/authLogin.cgi
/Users/guy/Library/Python/3.10/lib/python/site-packages/urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.1.11'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
DEBUG: Request executed: 404
DEBUG: GET from URL: https://192.168.1.11:443/cgi-bin/authLogin.cgi?user=master&pwd=ZXNrYWhzdGVmYW4=
/Users/guy/Library/Python/3.10/lib/python/site-packages/urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.1.11'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
DEBUG: Request executed: 404
DEBUG: Login failed, unable to process request
DEBUG: GET from URL: https://192.168.1.11:443/cgi-bin/disk/qsmart.cgi?func=all_hd_data
('can only concatenate str (not "NoneType") to str',)
Traceback (most recent call last):
  File "/Users/guy/Library/Application Support/CodeRunner/Unsaved/Untitled 7.py", line 28, in <module>
    qnap.get_smart_disk_health()
  File "/Users/guy/Library/Python/3.10/lib/python/site-packages/qnapstats/qnap_stats.py", line 194, in get_smart_disk_health
    resp = self._get_url("disk/qsmart.cgi?func=all_hd_data", force_list=("entry"))
  File "/Users/guy/Library/Python/3.10/lib/python/site-packages/qnapstats/qnap_stats.py", line 76, in _get_url
    result = self._execute_get_url(url, **kwargs)
  File "/Users/guy/Library/Python/3.10/lib/python/site-packages/qnapstats/qnap_stats.py", line 89, in _execute_get_url
    self._debuglog("Appending access_token (SID: " + self._sid + ") to url")
TypeError: can only concatenate str (not "NoneType") to str
DEBUG: Creating new session
DEBUG: POST to URL: https://192.168.1.11:443/cgi-bin/authLogin.cgi
/Users/guy/Library/Python/3.10/lib/python/site-packages/urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.1.11'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
DEBUG: Request executed: 404
DEBUG: GET from URL: https://192.168.1.11:443/cgi-bin/authLogin.cgi?user=master&pwd=ZXNrYWhzdGVmYW4=
/Users/guy/Library/Python/3.10/lib/python/site-packages/urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.1.11'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
DEBUG: Request executed: 404
DEBUG: Login failed, unable to process request
DEBUG: GET from URL: https://192.168.1.11:443/cgi-bin/management/chartReq.cgi?chart_func=disk_usage&disk_select=all&include=all
('can only concatenate str (not "NoneType") to str',)
Traceback (most recent call last):
  File "/Users/guy/Library/Application Support/CodeRunner/Unsaved/Untitled 7.py", line 34, in <module>
    qnap.get_volumes()
  File "/Users/guy/Library/Python/3.10/lib/python/site-packages/qnapstats/qnap_stats.py", line 142, in get_volumes
    resp = self._get_url(
  File "/Users/guy/Library/Python/3.10/lib/python/site-packages/qnapstats/qnap_stats.py", line 76, in _get_url
    result = self._execute_get_url(url, **kwargs)
  File "/Users/guy/Library/Python/3.10/lib/python/site-packages/qnapstats/qnap_stats.py", line 89, in _execute_get_url
    self._debuglog("Appending access_token (SID: " + self._sid + ") to url")
TypeError: can only concatenate str (not "NoneType") to str
DEBUG: Creating new session
DEBUG: POST to URL: https://192.168.1.11:443/cgi-bin/authLogin.cgi
/Users/guy/Library/Python/3.10/lib/python/site-packages/urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.1.11'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
DEBUG: Request executed: 404
DEBUG: GET from URL: https://192.168.1.11:443/cgi-bin/authLogin.cgi?user=master&pwd=ZXNrYWhzdGVmYW4=
/Users/guy/Library/Python/3.10/lib/python/site-packages/urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.1.11'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
DEBUG: Request executed: 404
DEBUG: Login failed, unable to process request
DEBUG: GET from URL: https://192.168.1.11:443/cgi-bin/management/chartReq.cgi?chart_func=QSM40bandwidth
('can only concatenate str (not "NoneType") to str',)
Traceback (most recent call last):
  File "/Users/guy/Library/Application Support/CodeRunner/Unsaved/Untitled 7.py", line 40, in <module>
    qnap.get_bandwidth()
  File "/Users/guy/Library/Python/3.10/lib/python/site-packages/qnapstats/qnap_stats.py", line 288, in get_bandwidth
    resp = self._get_url(
  File "/Users/guy/Library/Python/3.10/lib/python/site-packages/qnapstats/qnap_stats.py", line 76, in _get_url
    result = self._execute_get_url(url, **kwargs)
  File "/Users/guy/Library/Python/3.10/lib/python/site-packages/qnapstats/qnap_stats.py", line 89, in _execute_get_url
    self._debuglog("Appending access_token (SID: " + self._sid + ") to url")
TypeError: can only concatenate str (not "NoneType") to str
("'QNAPStats' object has no attribute 'get_external_drive'",)
Traceback (most recent call last):
  File "/Users/guy/Library/Application Support/CodeRunner/Unsaved/Untitled 7.py", line 46, in <module>
    qnap.get_external_drive()
AttributeError: 'QNAPStats' object has no attribute 'get_external_drive'
("'QNAPStats' object has no attribute 'get_storage_information_on_external_device'",)
Traceback (most recent call last):
  File "/Users/guy/Library/Application Support/CodeRunner/Unsaved/Untitled 7.py", line 53, in <module>
    qnap.get_storage_information_on_external_device()
AttributeError: 'QNAPStats' object has no attribute 'get_storage_information_on_external_device'
```

FWIW, I am using a self-signed certificate...

**Comment by idominiki** [comment]
Problem still exists.
