### ISSUE TITLE
KeyError: 'cpu_tempc' in get_system_stats on TS-410 (4.2.3)

### ISSUE THREAD

**Issue by Atrejoe** [colinodell/python-qnapstats#8]
Similar to #4 , requesting `qnap.get_system_stats()` results in: 
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.4/dist-packages/qnapstats/qnap_stats.py", line 236, in get_system_stats
    "temp_c": int(root["cpu_tempc"]),
KeyError: 'cpu_tempc'
```
Using a TS-410 running 4.2.3

**Comment by Atrejoe** [comment]
This also happened when requesting `qnap.get_volumes()` (key error indicates `volumeLabel`)

**Comment by Atrejoe** [comment]
And `qnap.get_smart_disk_health()` results in key error hd_is_ssd. Looking at the source code is see that probably `cgi-bin/management/chartReq.cgi?chart_func=disk_usage&disk_select=all&include=all` is called, in my case returning:

```
<?xml version="1.0" encoding="UTF-8" ?>
<QDocRoot version="1.0">
<authPassed><![CDATA[0]]></authPassed></QDocRoot>```

Testing some of the other queries I see in the source (which I do not see passing by when) viewing the web administration page, receive the same response.

Is there some config on the NAS I'm missing, or is this maybe not supported by my NAS?

Other methods like tracing network statistics using `qnap.get_bandwidth()` does work and is snappy.

When specifying 'debugmode=true' I do see some debugging information, but not the content of the response, as I would expect reading the source. But I see that the line displaying such debug information is added after release 2.2

**Comment by colinodell** [comment]
Sorry for the delayed response, I've just returned from a week-long holiday.

The `hd_is_ssd` and `volumeLabel` issues should be resolved in `master`.

To resolve the `cpu_tempc` issue I'll need to see the XML your QNAP device is providing for `/cgi-bin/management/manaRequest.cgi?subfunc=sysinfo&hd=no&multicpu=1`.  (I just added a new script to this repository named [debug.py](debug.py) which can help you obtain that)

**Comment by Atrejoe** [comment]
`/cgi-bin/management/manaRequest.cgi?subfunc=sysinfo&hd=no&multicpu=1`

returns

```<QDocRoot version="1.0">
<authPassed>
<![CDATA[ 0 ]]>
</authPassed>
</QDocRoot>
```

In the visual management interface I do not see the temp listed either. When monitor the traffic in my browser some time, looking for manaRequest, I do not see the subfunc 'sysinfo' pass.

![image](https://cloud.githubusercontent.com/assets/585091/23166000/11f6c31e-f83f-11e6-9c1f-83c5fba31923.png)

![image](https://cloud.githubusercontent.com/assets/585091/23166013/2b7ff8a0-f83f-11e6-9eaa-89f1ed9626e3.png)

**Comment by colinodell** [comment]
`<authPassed>` containing a value of `0` indicates that you didn't provide a valid session id (`sid`).

Monitor the requests in your browser again, but look for `&sid=` in the URL.  It should have some random letters/numbers after it like this: `&sid=846w45fh`

Append that to the end of `/cgi-bin/management/manaRequest.cgi?subfunc=sysinfo&hd=no&multicpu=1` like so:

```
/cgi-bin/management/manaRequest.cgi?subfunc=sysinfo&hd=no&multicpu=1&sid=846w45fh
```

You should end up with a longer response.

**Comment by Atrejoe** [comment]
That helps, still no cpu_tempc though:
```<?xml version="1.0" encoding="UTF-8" ?>
<QDocRoot version="1.0">
<authPassed><![CDATA[1]]></authPassed><model><modelName><![CDATA[TS-410]]></modelName><internalModelName><![CDATA[TS-419]]></internalModelName><platform><![CDATA[TS-NASARM]]></platform><customModelName><![CDATA[]]></customModelName><displayModelName><![CDATA[TS-410]]></displayModelName><storage_v2>0</storage_v2>
</model>
<firmware><version><![CDATA[4.2.3]]></version><build><![CDATA[20170121]]></build><patch><![CDATA[0]]></patch><buildTime><![CDATA[21-01-2017]]></buildTime></firmware>
<specVersion><![CDATA[1.0]]></specVersion><hostname><![CDATA[MYHOSTNAME]]></hostname><DemoSiteSuppurt><![CDATA[no]]></DemoSiteSuppurt><customLogo><customFrontLogo><![CDATA[]]></customFrontLogo><customLoginLogo><![CDATA[]]></customLoginLogo></customLogo>
<func><name><![CDATA[S_MENU_40]]></name><ownContent><root><timezone><![CDATA[(GMT+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna]]></timezone><cpu_usage><![CDATA[48.5 %]]></cpu_usage><total_memory><![CDATA[249.6]]></total_memory><free_memory><![CDATA[60.8]]></free_memory><nic_cnt><![CDATA[2]]></nic_cnt><rx_packet1>193439491</rx_packet1>
<tx_packet1>123234929</tx_packet1>
<err_packet1>0</err_packet1>
<eth_status1>1</eth_status1>
<eth_max_speed1>1000</eth_max_speed1>
<eth_ip1>192.168.1.101</eth_ip1>
<eth_mask1>255.255.255.0</eth_mask1>
<eth_mac1>00:08:9B:C1:80:6A</eth_mac1>
<eth_usage1>DHCP</eth_usage1>
<rx_packet2>0</rx_packet2>
<tx_packet2>0</tx_packet2>
<err_packet2>0</err_packet2>
<eth_status2>0</eth_status2>
<eth_max_speed2>1000</eth_max_speed2>
<eth_ip2>0.0.0.0</eth_ip2>
<eth_mask2>0.0.0.0</eth_mask2>
<eth_mac2>00:08:9B:C1:80:6B</eth_mac2>
<eth_usage2>DHCP</eth_usage2>
<ipv6Enable><![CDATA[0]]></ipv6Enable><dnsInfo><DNS_LIST><![CDATA[ 192.168.1.1
]]></DNS_LIST></dnsInfo>
<WirelessSupport><![CDATA[1]]></WirelessSupport><Error><![CDATA[1]]></Error><ThunderboltSupport><![CDATA[0]]></ThunderboltSupport><uptime_day><![CDATA[13]]></uptime_day><uptime_hour><![CDATA[17]]></uptime_hour><uptime_min><![CDATA[47]]></uptime_min><uptime_sec><![CDATA[48]]></uptime_sec><HDTempWarnT><![CDATA[55]]></HDTempWarnT><HDTempErrT><![CDATA[60]]></HDTempErrT><SSDTempWarnT><![CDATA[65]]></SSDTempWarnT><SSDTempErrT><![CDATA[70]]></SSDTempErrT><sys_tempc>40</sys_tempc>
<sys_tempf>104</sys_tempf>
<SysTempWarnT><![CDATA[57]]></SysTempWarnT><SysTempErrT><![CDATA[70]]></SysTempErrT><sysfan_count>0</sysfan_count>
<serial_number>MYSERIAL</serial_number>
<server_name><![CDATA[hornbill]]></server_name><codepage><![CDATA[437]]></codepage></root>
</ownContent>
</func>
</QDocRoot>```

**Comment by Atrejoe** [comment]
(side not, you see that the TS-410 is quite slow, I think the response timeout should be enlarged somewhat)

**Comment by colinodell** [comment]
Thanks for the extra details!  I've fixed the issue here and will work on getting it into HASS as well.

**Comment by colinodell** [comment]
I also made the timeout configurable in #10.  Will get that into HASS too.
